<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Casper.DataForge.CrossPlatform\Casper.DataForge.CrossPlatform.csproj" />
    <Content Include="..\..\src\Casper.DataForge.CrossPlatform\Assets\KnowledgeBase\**">
      <Link>Assets\KnowledgeBase\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
